import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import MainLayout from 'src/components/layout/MainLayout'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
          <h1>CONTENIDO</h1>
      </MainLayout>
    </>
  )
}

export default Home

export async function getStaticProps(context: any) {
  return {
    props: {
      // You can get the messages from anywhere you like. The recommended
      // pattern is to put them in JSON files separated by language.
      messages: (await import(`/locale/${context.locale}/common.json`)).default
    }
  };
}