import type { NextPage } from 'next'
import Head from 'next/head'
import HomeLayout from 'src/layout/home'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
        
      </HomeLayout>
    </>
  )
}

export default Home

export async function getStaticProps(context: any) {
  return {
    props: {
      // You can get the messages from anywhere you like. The recommended
      // pattern is to put them in JSON files separated by language.
      messages: (await import(`/locale/${context.locale}/common.json`)).default
    }
  };
}